"""Behavior-tree XML generated from ``behavior_tree`` templates.

The trees follow Nav2's stock ``navigate_to_pose_w_replanning_and_recovery.xml``
and ``navigate_through_poses_w_replanning_and_recovery.xml`` so they work with
an unmodified ``bt_navigator`` (Iron and newer). Each mission step can carry
its own tree; the runner writes it under ``<home>/bt/`` at deploy time and
sends the path with the goal.
"""

from __future__ import annotations

import math
import re
from typing import Any

__all__ = ["TEMPLATES", "render_behavior_tree", "bt_file_name", "template_defaults"]

TEMPLATES = ("navigate_with_recovery", "navigate_through_poses_with_recovery")

_DEFAULTS: dict[str, Any] = {
    "retries": 6,
    "recoveries": ["clear_costmap", "spin", "wait", "backup"],
    "replan_rate_hz": 1.0,
    "spin_deg": 90.0,
    "backup_m": 0.3,
    "wait_s": 5.0,
    "planner_id": "GridBased",
    "controller_id": "FollowPath",
}


def template_defaults() -> dict[str, Any]:
    return {k: (list(v) if isinstance(v, list) else v) for k, v in _DEFAULTS.items()}


def bt_file_name(mission: str, step_id: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_-]", "_", f"{mission}__{step_id}")
    return f"{safe}.xml"


def _fmt(v: float) -> str:
    return f"{float(v):.4g}"


def render_behavior_tree(spec: dict[str, Any]) -> str:
    """Return the XML for a ``behavior_tree`` template object."""
    cfg = {**_DEFAULTS, **{k: v for k, v in spec.items() if v is not None}}
    template = cfg.get("template", TEMPLATES[0])
    if template not in TEMPLATES:
        raise ValueError(f"unknown behavior tree template '{template}'")
    retries = int(cfg["retries"])
    rate = float(cfg["replan_rate_hz"])
    planner = str(cfg["planner_id"])
    controller = str(cfg["controller_id"])
    recoveries = [r for r in cfg["recoveries"] if r in ("clear_costmap", "spin", "wait", "backup")]

    if template == "navigate_with_recovery":
        compute = (
            f'          <RecoveryNode number_of_retries="1" name="ComputePathToPose">\n'
            f'            <ComputePathToPose goal="{{goal}}" path="{{path}}" planner_id="{planner}" error_code_id="{{compute_path_error_code}}"/>\n'
            f'            <ClearEntireCostmap name="ClearGlobalCostmap-Context" service_name="global_costmap/clear_entirely_global_costmap"/>\n'
            f"          </RecoveryNode>\n"
        )
    else:
        compute = (
            f'          <RecoveryNode number_of_retries="1" name="ComputePathThroughPoses">\n'
            f"            <ReactiveSequence>\n"
            f'              <RemovePassedGoals input_goals="{{goals}}" output_goals="{{goals}}" radius="0.7"/>\n'
            f'              <ComputePathThroughPoses goals="{{goals}}" path="{{path}}" planner_id="{planner}" error_code_id="{{compute_path_error_code}}"/>\n'
            f"            </ReactiveSequence>\n"
            f'            <ClearEntireCostmap name="ClearGlobalCostmap-Context" service_name="global_costmap/clear_entirely_global_costmap"/>\n'
            f"          </RecoveryNode>\n"
        )

    recovery_nodes: list[str] = []
    for r in recoveries:
        if r == "clear_costmap":
            recovery_nodes.append(
                '          <Sequence name="ClearingActions">\n'
                '            <ClearEntireCostmap name="ClearLocalCostmap-Subtree" service_name="local_costmap/clear_entirely_local_costmap"/>\n'
                '            <ClearEntireCostmap name="ClearGlobalCostmap-Subtree" service_name="global_costmap/clear_entirely_global_costmap"/>\n'
                "          </Sequence>\n"
            )
        elif r == "spin":
            recovery_nodes.append(f'          <Spin spin_dist="{_fmt(math.radians(float(cfg["spin_deg"])))}" error_code_id="{{spin_error_code}}"/>\n')
        elif r == "wait":
            recovery_nodes.append(f'          <Wait wait_duration="{_fmt(float(cfg["wait_s"]))}" error_code_id="{{wait_error_code}}"/>\n')
        elif r == "backup":
            recovery_nodes.append(f'          <BackUp backup_dist="{_fmt(float(cfg["backup_m"]))}" backup_speed="0.05" error_code_id="{{backup_error_code}}"/>\n')

    if recovery_nodes:
        fallback = (
            '      <ReactiveFallback name="RecoveryFallback">\n'
            "        <GoalUpdated/>\n"
            '        <RoundRobin name="RecoveryActions">\n'
            + "".join(recovery_nodes)
            + "        </RoundRobin>\n"
            "      </ReactiveFallback>\n"
        )
    else:
        fallback = '      <AlwaysFailure name="NoRecovery"/>\n'

    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"<!-- generated by mission_runner: template={template} retries={retries} recoveries={','.join(recoveries) or 'none'} -->\n"
        '<root BTCPP_format="4" main_tree_to_execute="MainTree">\n'
        '  <BehaviorTree ID="MainTree">\n'
        f'    <RecoveryNode number_of_retries="{retries}" name="NavigateRecovery">\n'
        '      <PipelineSequence name="NavigateWithReplanning">\n'
        f'        <RateController hz="{_fmt(rate)}">\n'
        + compute
        + "        </RateController>\n"
        '        <RecoveryNode number_of_retries="1" name="FollowPath">\n'
        f'          <FollowPath path="{{path}}" controller_id="{controller}" error_code_id="{{follow_path_error_code}}"/>\n'
        '          <ClearEntireCostmap name="ClearLocalCostmap-Context" service_name="local_costmap/clear_entirely_local_costmap"/>\n'
        "        </RecoveryNode>\n"
        "      </PipelineSequence>\n"
        + fallback
        + "    </RecoveryNode>\n"
        "  </BehaviorTree>\n"
        "</root>\n"
    )
